version: '3.8'

services:
  
  db:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysqldata:
